### ISSUE TITLE
After you die you may get detected before the game actually started

### ISSUE THREAD

**Issue by Hexaae** [AFADoomer/Wolf3D-TC-3.0#20]
Try Spear of Destiny (first map at difficulty Death Incarnate); after you get killed in the very first room the game as usual will run the red death sequence and reload, and if you pay attention the shouting Nazis (when they spot the player!) will start even before the Get Psyched screen... definitely too early!

**Comment by AFADoomer** [comment]
Should be fixed in b497dacd47fced4cf0d505667f9661d132b1c46b.

**Comment by Hexaae** [comment]
Still a bit more delay maybe? I hear them shouting when the fizzle effect is still not completely over.

Another thing with b497dac: after final death, on Main Menu if you select New the game will show in background your last 3D view for a moment during menu transitions...

P.S.
Did you set black screen for high scores! Great! 🎉

**Comment by AFADoomer** [comment]
I can't fix the 'New Game' single-frame showing - that's GZDoom.

The others should be good in 9f44a102c89ecfa94c6731960bf8350b3e124653.

If your fizzle fade is taking too long with your current hardware, I also added a CVar to allow the player to scale that speed in 528c6e11ba7cca205301b45200b81da9081a2bdd.

**Comment by Hexaae** [comment]
> I can't fix the 'New Game' single-frame showing - that's GZDoom.

Mmmh, never seen it with other GZDoom TCs... needs more investigation...

> If your fizzle fade is taking too long with your current hardware, I also added a CVar to allow the player to scale that speed in [528c6e1](https://github.com/AFADoomer/Wolf3D-TC-3.0/commit/528c6e11ba7cca205301b45200b81da9081a2bdd).

The problem with Spear of Destiny remains. The problem happens only on 2nd, 3rd... deaths. The first time the game is loading the delay is ok (now it's too long IMHO, better before 9f44a10) and guards are still without AI for a moment as it should. The problem is on next re-start after you die again: the initial delay you added seems not be used at all on next deaths...
Repro steps:

- Run Spear of Destiny campaign at Death Incarnate difficulty level. Don't Move and let you get killed. Now on next re-start after you died the first time it's like that initial delay is not being used to me...

**Comment by AFADoomer** [comment]
Not investigating more.  GZDoom [literally closes all open menus when a new game starts](https://github.com/ZDoom/gzdoom/blob/f32279278356303ea1c0e12766737c7a97b1d7d4/src/menu/doommenu.cpp#L176), so you see the old screen for a tick before the level change kicks in.  You don't normally notice because most menus aren't drawn on a solid background, so it just looks like the menu text and fade color disappears for a tick and is less jarring of a change.

The guards are *supposed* to attack you immediately after the fizzle...  They are delayed while the fizzle is drawing.  If your fizzle is taking longer than 45 ticks (about 1.25 seconds), you need to adjust the CVar multiplier for the fizzle speed in the menu.

**Comment by AFADoomer** [comment]
Updated the delay logic in c6eb999a3f06ecc91669747f538984a34188067c.  Guards wait the same amount (plus or minus 1 tick) regardless of how the map starts.

**Comment by Hexaae** [comment]
Works fine now. Thank you!
P.S.
I tried to register on ZDoom forum to ask about menu transitions, but security questions were so hard and after 3 attempts won't let you try again...  😵
